[package]
name = "any-decoder"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bzip2 = "0.4.4"
flate2 = "1.0.33"
xz = "0.1.0"
zstd = "0.13.2"

[dev-dependencies]
arbitrary = { version = "1.4.1", features = ["derive", "derive_arbitrary"] }
arbtest = "0.3.1"

[features]
default = []
# Override methods only available in Rust Nightly.
nightly = []

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[lints.rust]
missing_docs = "warn"
